package eventoscientificos.view;

import eventoscientificos.controllers.CriarEventoController;
import eventoscientificos.model.Administrador;
import eventoscientificos.model.Empresa;
import eventoscientificos.model.Local;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import utils.Data;

/**
 * @author G01
 */
public class CriarEventoUI extends javax.swing.JDialog {

    private CriarEventoController controller;
    private Frame framePai;

    /**
     * Creates new form CriarEventoUI
     *
     * @param parent parent
     * @param modal modal
     * @param empresa empresa
     */
    public CriarEventoUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, "Criar Evento", modal);
        this.controller = new CriarEventoController(empresa);
        this.framePai = parent;
        setResizable(false);
        initComponents();
        getRootPane().setDefaultButton(btn_criarEvento);
        setLocationRelativeTo(null);
        if (!empresa.isAdministrador(new Administrador(
                empresa.getUtilizadorAutenticado()))) {
            JOptionPane.showMessageDialog(
                    framePai,
                    "Não tem permissões para criar eventos.",
                    "Criar Evento",
                    JOptionPane.ERROR_MESSAGE);
            dispose();
        } else {
            setVisible(true);
            pack();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_informacoes = new javax.swing.JPanel();
        txt_descricao = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        txt_local = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        lbl_descricao = new javax.swing.JLabel();
        lbl_local = new javax.swing.JLabel();
        pnl_datas = new javax.swing.JPanel();
        datePicker_dataFimSubmissaoCameraReady = new org.jdesktop.swingx.JXDatePicker();
        datePicker_dataInicio = new org.jdesktop.swingx.JXDatePicker();
        datePicker_dataInicioDistribuicao = new org.jdesktop.swingx.JXDatePicker();
        datePicker_dataInicioSubmissao = new org.jdesktop.swingx.JXDatePicker();
        datePicker_dataFimSubmissao = new org.jdesktop.swingx.JXDatePicker();
        datePicker_dataFim = new org.jdesktop.swingx.JXDatePicker();
        datePicker_dataFimRevisao = new org.jdesktop.swingx.JXDatePicker();
        lbl_dataInicioDistribuicao = new javax.swing.JLabel();
        lbl_dataFimRevisao = new javax.swing.JLabel();
        lbl_dataFimSubmissao = new javax.swing.JLabel();
        lbl_dataInicioSubmissao = new javax.swing.JLabel();
        lbl_dataFim = new javax.swing.JLabel();
        lbl_dataInicio = new javax.swing.JLabel();
        lbl_dataFimSubmissaoCameraReady = new javax.swing.JLabel();
        pnl_listaOrganizadores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_listaOrganizadores = new javax.swing.JList();
        btn_adicionarOrganizador = new javax.swing.JButton();
        txt_IDorganizador = new javax.swing.JTextField();
        lbl_IDorganizador = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_criarEvento = new javax.swing.JButton();
        btn_seguinte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_informacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        lbl_titulo.setText("Titulo:");

        lbl_descricao.setText("Descrição:");

        lbl_local.setText("Local:");

        javax.swing.GroupLayout pnl_informacoesLayout = new javax.swing.GroupLayout(pnl_informacoes);
        pnl_informacoes.setLayout(pnl_informacoesLayout);
        pnl_informacoesLayout.setHorizontalGroup(
            pnl_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbl_descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_local)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_local, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_informacoesLayout.setVerticalGroup(
            pnl_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descricao)
                    .addComponent(lbl_titulo)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_local)
                    .addComponent(txt_local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_datas.setBorder(javax.swing.BorderFactory.createTitledBorder("Datas"));

        datePicker_dataInicioSubmissao.setFocusCycleRoot(true);

        lbl_dataInicioDistribuicao.setText("Data de distribuição:");

        lbl_dataFimRevisao.setText("Data limite de revisão:");

        lbl_dataFimSubmissao.setText("Data final de submissão:");

        lbl_dataInicioSubmissao.setText("Data inicial de submissão:");

        lbl_dataFim.setText("Data de fim:");

        lbl_dataInicio.setText("Data de início:");

        lbl_dataFimSubmissaoCameraReady.setText("Data limite de submissão Camera Ready:");

        javax.swing.GroupLayout pnl_datasLayout = new javax.swing.GroupLayout(pnl_datas);
        pnl_datas.setLayout(pnl_datasLayout);
        pnl_datasLayout.setHorizontalGroup(
            pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_datasLayout.createSequentialGroup()
                        .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_dataInicio)
                            .addComponent(lbl_dataFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePicker_dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePicker_dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_dataInicioSubmissao)
                            .addComponent(lbl_dataFimSubmissao))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePicker_dataFimSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePicker_dataInicioSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasLayout.createSequentialGroup()
                                .addComponent(lbl_dataFimRevisao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datePicker_dataFimRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasLayout.createSequentialGroup()
                                .addComponent(lbl_dataInicioDistribuicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datePicker_dataInicioDistribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_datasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_dataFimSubmissaoCameraReady)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datePicker_dataFimSubmissaoCameraReady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_datasLayout.setVerticalGroup(
            pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dataInicio)
                    .addComponent(datePicker_dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker_dataInicioSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataInicioDistribuicao)
                    .addComponent(datePicker_dataInicioDistribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataInicioSubmissao))
                .addGap(18, 18, 18)
                .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dataFim)
                    .addComponent(lbl_dataFimSubmissao)
                    .addComponent(datePicker_dataFimSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataFimRevisao)
                    .addComponent(datePicker_dataFimRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker_dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_datasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePicker_dataFimSubmissaoCameraReady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataFimSubmissaoCameraReady))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pnl_listaOrganizadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Organizadores"));
        pnl_listaOrganizadores.setName(""); // NOI18N
        pnl_listaOrganizadores.setVisible(false);

        jList_listaOrganizadores.setModel(this.controller.getModeloListaPapel());
        jList_listaOrganizadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList_listaOrganizadores.setToolTipText("");
        jScrollPane1.setViewportView(jList_listaOrganizadores);

        btn_adicionarOrganizador.setText("Adicionar Organizador");
        btn_adicionarOrganizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarOrganizadorActionPerformed(evt);
            }
        });

        lbl_IDorganizador.setText("Insira o ID do organizador:");

        javax.swing.GroupLayout pnl_listaOrganizadoresLayout = new javax.swing.GroupLayout(pnl_listaOrganizadores);
        pnl_listaOrganizadores.setLayout(pnl_listaOrganizadoresLayout);
        pnl_listaOrganizadoresLayout.setHorizontalGroup(
            pnl_listaOrganizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listaOrganizadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_listaOrganizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnl_listaOrganizadoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_IDorganizador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_IDorganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_adicionarOrganizador)))
                .addContainerGap())
        );
        pnl_listaOrganizadoresLayout.setVerticalGroup(
            pnl_listaOrganizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listaOrganizadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_listaOrganizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adicionarOrganizador)
                    .addComponent(txt_IDorganizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_IDorganizador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_criarEvento.setText("Criar Evento");
        btn_criarEvento.setVisible(false);
        btn_criarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarEventoActionPerformed(evt);
            }
        });

        btn_seguinte.setText("Seguinte");
        btn_seguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seguinteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_informacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_datas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_listaOrganizadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_seguinte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_criarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_datas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_listaOrganizadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_criarEvento)
                    .addComponent(btn_seguinte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_criarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarEventoActionPerformed
        try {
            this.controller.validarEvento();

            String opcoes[] = {"Sim", "Não"};
            int resposta = JOptionPane.showOptionDialog(
                    null, "Pretende criar o evento?", "Criar Evento", 0,
                    JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
            if (resposta == 0) {
                this.controller.adicionarEvento();
            }
            dispose();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    "Criar Evento",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_criarEventoActionPerformed

    private void btn_adicionarOrganizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarOrganizadorActionPerformed
        try {
            this.controller.novoOrganizador(txt_IDorganizador.getText());

            txt_IDorganizador.setText("");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    "Não introduziu um ID válido.",
                    "Criar Evento",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    "Criar Evento",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_adicionarOrganizadorActionPerformed

    private void btn_seguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seguinteActionPerformed
        try {
            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");

            this.controller.novoEvento(
                    txt_titulo.getText(),
                    txt_descricao.getText(),
                    new Local(txt_local.getText()),
                    Data.converterString(formatador.format(datePicker_dataInicioSubmissao.getDate())),
                    Data.converterString(formatador.format(datePicker_dataFimSubmissao.getDate())),
                    Data.converterString(formatador.format(datePicker_dataInicioDistribuicao.getDate())),
                    Data.converterString(formatador.format(datePicker_dataFimRevisao.getDate())),
                    Data.converterString(formatador.format(datePicker_dataFimSubmissaoCameraReady.getDate())),
                    Data.converterString(formatador.format(datePicker_dataInicio.getDate())),
                    Data.converterString(formatador.format(datePicker_dataFim.getDate())));

            this.pnl_informacoes.setVisible(false);
            this.pnl_datas.setVisible(false);
            this.btn_seguinte.setVisible(false);
            this.pnl_listaOrganizadores.setVisible(true);
            this.btn_criarEvento.setVisible(true);
            pack();
            setLocationRelativeTo(null);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    "Criar Evento",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(
                    framePai,
                    "Existem datas por preencher.",
                    "Criar Evento",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_seguinteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionarOrganizador;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_criarEvento;
    private javax.swing.JButton btn_seguinte;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataFim;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataFimRevisao;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataFimSubmissao;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataFimSubmissaoCameraReady;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataInicio;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataInicioDistribuicao;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataInicioSubmissao;
    private javax.swing.JList jList_listaOrganizadores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_IDorganizador;
    private javax.swing.JLabel lbl_dataFim;
    private javax.swing.JLabel lbl_dataFimRevisao;
    private javax.swing.JLabel lbl_dataFimSubmissao;
    private javax.swing.JLabel lbl_dataFimSubmissaoCameraReady;
    private javax.swing.JLabel lbl_dataInicio;
    private javax.swing.JLabel lbl_dataInicioDistribuicao;
    private javax.swing.JLabel lbl_dataInicioSubmissao;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_local;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_datas;
    private javax.swing.JPanel pnl_informacoes;
    private javax.swing.JPanel pnl_listaOrganizadores;
    private javax.swing.JTextField txt_IDorganizador;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_local;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
