package eventoscientificos.view;

import eventoscientificos.controllers.GerarAnaliseEstatisticaRevisaoController;
import eventoscientificos.model.Administrador;
import eventoscientificos.model.Empresa;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 * @author G01
 */
public class GerarAnaliseEstatisticaRevisaoUI extends javax.swing.JDialog {

    private Frame framePai;
    private GerarAnaliseEstatisticaRevisaoController controller;

    public GerarAnaliseEstatisticaRevisaoUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, modal);
        this.framePai = parent;
        this.controller = new GerarAnaliseEstatisticaRevisaoController(empresa);
        this.controller.gerarAnaliseEstatisticas();
        setResizable(false);
        getRootPane().setDefaultButton(this.btn_notificar);
        setLocationRelativeTo(null);
        initComponents();
        if (!empresa.isAdministrador(
                new Administrador(empresa.getUtilizadorAutenticado()))) {
            JOptionPane.showMessageDialog(
                    framePai,
                    "Não tem permissões para submeter artigos a partir de"
                    + "ficheiros.",
                    "Gerar Estatistica Revisor",
                    JOptionPane.ERROR_MESSAGE);
            dispose();
        } else if (this.controller.getResultadosFinais().length < 0) {
            JOptionPane.showMessageDialog(
                    framePai,
                    "Não existem submissões aceites!",
                    "Gerar Estatistica Revisor",
                    JOptionPane.ERROR_MESSAGE);
            dispose();

        } else {
            setVisible(true);
            pack();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        List_revisores = new javax.swing.JList(this.controller.getResultadosFinais());
        btn_notificar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        List_revisores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        List_revisores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(List_revisores);

        btn_notificar.setText("Notificar Organizadores");
        btn_notificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notificarActionPerformed(evt);
            }
        });

        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 634, Short.MAX_VALUE)
                        .addComponent(btn_notificar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sair)
                    .addComponent(btn_notificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_notificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notificarActionPerformed
        int indice = this.List_revisores.getSelectedIndex();

        if (this.controller.notificarOrganizadoresEventos(indice)) {
            new NotificacoesUI(this.framePai, true, this.controller.getListaEmail());
        }
    }//GEN-LAST:event_btn_notificarActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList List_revisores;
    private javax.swing.JButton btn_notificar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
