/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventoscientificos.view;

import eventoscientificos.controllers.ControllerAutor;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class NovoAutor extends javax.swing.JDialog {

    private ControllerAutor controller;

    /**
     * Creates new form NovoAutor
     *
     * @param parent parent
     * @param modal modal
     * @param controller controller
     */
    public NovoAutor(java.awt.Frame parent, boolean modal, ControllerAutor controller) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
        getRootPane().setDefaultButton(this.btn_adicionarAutor);
        setLocationRelativeTo(null);
        setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_nome = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        pnl_email = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        pnl_instituicao = new javax.swing.JPanel();
        txt_instituicao = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        btn_adicionarAutor = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_nome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        pnl_nome.setPreferredSize(new java.awt.Dimension(280, 65));

        javax.swing.GroupLayout pnl_nomeLayout = new javax.swing.GroupLayout(pnl_nome);
        pnl_nome.setLayout(pnl_nomeLayout);
        pnl_nomeLayout.setHorizontalGroup(
            pnl_nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_nomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nome)
                .addContainerGap())
        );
        pnl_nomeLayout.setVerticalGroup(
            pnl_nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_nomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_email.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        pnl_email.setToolTipText("");
        pnl_email.setPreferredSize(new java.awt.Dimension(280, 65));

        javax.swing.GroupLayout pnl_emailLayout = new javax.swing.GroupLayout(pnl_email);
        pnl_email.setLayout(pnl_emailLayout);
        pnl_emailLayout.setHorizontalGroup(
            pnl_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_email)
                .addContainerGap())
        );
        pnl_emailLayout.setVerticalGroup(
            pnl_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_instituicao.setBorder(javax.swing.BorderFactory.createTitledBorder("Instituição de Afiliação"));
        pnl_instituicao.setPreferredSize(new java.awt.Dimension(280, 65));

        javax.swing.GroupLayout pnl_instituicaoLayout = new javax.swing.GroupLayout(pnl_instituicao);
        pnl_instituicao.setLayout(pnl_instituicaoLayout);
        pnl_instituicaoLayout.setHorizontalGroup(
            pnl_instituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_instituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_instituicao)
                .addContainerGap())
        );
        pnl_instituicaoLayout.setVerticalGroup(
            pnl_instituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_instituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_adicionarAutor.setText("Adicionar Autor");
        btn_adicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_instituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 92, Short.MAX_VALUE)
                        .addComponent(btn_adicionarAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_instituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_adicionarAutor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarAutorActionPerformed
        String nome = this.txt_nome.getText();
        String email = this.txt_email.getText();
        String instituicao = this.txt_instituicao.getText();

        try {
            this.controller.novoAutor(nome, email, instituicao);
            dispose();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Adicionar autor",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_adicionarAutorActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionarAutor;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_email;
    private javax.swing.JPanel pnl_instituicao;
    private javax.swing.JPanel pnl_nome;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_instituicao;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
