package eventoscientificos.view;

import eventoscientificos.controllers.RetirarSubmissaoController;
import eventoscientificos.model.Empresa;
import eventoscientificos.model.Submissao;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 * @author G01
 */
public class RetirarSubmissaoUI extends javax.swing.JDialog {

    private Frame framePai;
    private RetirarSubmissaoController controller;

    /**
     * Creates new form RetirarSubmissaoUI
     *
     * @param parent parent
     * @param modal modal
     * @param empresa empresa
     */
    public RetirarSubmissaoUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, "Retirar Submissão", modal);
        this.framePai = parent;
        this.controller = new RetirarSubmissaoController(empresa);
        this.controller.getListaSubmissiveisComArtigosUtilizadorParaRemover();
        setResizable(false);
        initComponents();
        getRootPane().setDefaultButton(this.btn_selecionarSubmissivel);
        setLocationRelativeTo(null);
        if (controller.getListaSubmissiveis().isEmpty()) {
            JOptionPane.showMessageDialog(framePai, "Não existem eventos ou "
                    + "sessões temáticas onde lhe é possível remover submissões.",
                    "Remover Submissão",
                    JOptionPane.ERROR_MESSAGE);
            dispose();
        } else {
            setVisible(true);
            pack();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_selecionarSubmissivel = new javax.swing.JPanel();
        cmb_selecionarSubmissivel = new javax.swing.JComboBox(this.controller.getListaSubmissiveis().toArray());
        btn_selecionarSubmissivel = new javax.swing.JButton();
        pnl_selecionarSubmissao = new javax.swing.JPanel();
        cmb_selecionarSubmissao = new javax.swing.JComboBox();
        btn_selecionarSubmissao = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_removerSubmissao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_selecionarSubmissivel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o evento/sessão temática do qual pretende remover uma submissão"));
        pnl_selecionarSubmissivel.setPreferredSize(new java.awt.Dimension(780, 68));

        btn_selecionarSubmissivel.setText("Selecionar");
        btn_selecionarSubmissivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionarSubmissivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_selecionarSubmissivelLayout = new javax.swing.GroupLayout(pnl_selecionarSubmissivel);
        pnl_selecionarSubmissivel.setLayout(pnl_selecionarSubmissivelLayout);
        pnl_selecionarSubmissivelLayout.setHorizontalGroup(
            pnl_selecionarSubmissivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_selecionarSubmissivelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_selecionarSubmissivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_selecionarSubmissivel)
                .addContainerGap())
        );
        pnl_selecionarSubmissivelLayout.setVerticalGroup(
            pnl_selecionarSubmissivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_selecionarSubmissivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_selecionarSubmissivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_selecionarSubmissivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selecionarSubmissivel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_selecionarSubmissao.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a submissão que pretende remover"));
        pnl_selecionarSubmissao.setPreferredSize(new java.awt.Dimension(780, 68));

        cmb_selecionarSubmissao.setEnabled(false);

        btn_selecionarSubmissao.setText("Selecionar");
        btn_selecionarSubmissao.setEnabled(false);
        btn_selecionarSubmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionarSubmissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_selecionarSubmissaoLayout = new javax.swing.GroupLayout(pnl_selecionarSubmissao);
        pnl_selecionarSubmissao.setLayout(pnl_selecionarSubmissaoLayout);
        pnl_selecionarSubmissaoLayout.setHorizontalGroup(
            pnl_selecionarSubmissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_selecionarSubmissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_selecionarSubmissao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_selecionarSubmissao)
                .addContainerGap())
        );
        pnl_selecionarSubmissaoLayout.setVerticalGroup(
            pnl_selecionarSubmissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_selecionarSubmissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_selecionarSubmissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_selecionarSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selecionarSubmissao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_removerSubmissao.setText("Remover Submissão");
        btn_removerSubmissao.setEnabled(false);
        btn_removerSubmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerSubmissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_selecionarSubmissivel, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                    .addComponent(pnl_selecionarSubmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 566, Short.MAX_VALUE)
                        .addComponent(btn_removerSubmissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_selecionarSubmissivel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_selecionarSubmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_removerSubmissao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selecionarSubmissivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionarSubmissivelActionPerformed
        int indice = this.cmb_selecionarSubmissivel.getSelectedIndex();
        this.controller.selecionarSubmissivel(indice);
        
        for (Submissao submissao : this.controller.getListaSubmissoes()) {
            this.cmb_selecionarSubmissao.addItem(submissao);
        }

        this.cmb_selecionarSubmissivel.setEnabled(false);
        this.btn_selecionarSubmissivel.setEnabled(false);
        this.cmb_selecionarSubmissao.setEnabled(true);
        this.btn_selecionarSubmissao.setEnabled(true);
        getRootPane().setDefaultButton(this.btn_selecionarSubmissao);
        
    }//GEN-LAST:event_btn_selecionarSubmissivelActionPerformed

    private void btn_selecionarSubmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionarSubmissaoActionPerformed
        int indice = this.cmb_selecionarSubmissao.getSelectedIndex();
        this.controller.selecionaSubmissao(indice);
        
        this.cmb_selecionarSubmissao.setEnabled(false);
        this.btn_selecionarSubmissao.setEnabled(false);
        this.btn_removerSubmissao.setEnabled(true);
        getRootPane().setDefaultButton(this.btn_removerSubmissao);
    }//GEN-LAST:event_btn_selecionarSubmissaoActionPerformed

    private void btn_removerSubmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerSubmissaoActionPerformed
        String opcoes[] = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(
                this, "Pretende retirar a submissão selecionada?", "Retirar Submissão", 0,
                JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
        if (resposta == 0) {
            this.controller.removerSubmissao();
        }
        dispose();
    }//GEN-LAST:event_btn_removerSubmissaoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_removerSubmissao;
    private javax.swing.JButton btn_selecionarSubmissao;
    private javax.swing.JButton btn_selecionarSubmissivel;
    private javax.swing.JComboBox cmb_selecionarSubmissao;
    private javax.swing.JComboBox cmb_selecionarSubmissivel;
    private javax.swing.JPanel pnl_selecionarSubmissao;
    private javax.swing.JPanel pnl_selecionarSubmissivel;
    // End of variables declaration//GEN-END:variables
}
